#' Clustering with the optimal parameters estimated by these tools
#'
#' @param data A dataframe, where columns are features and rows are data points
#' @param clusters Number of clusters to be generated by this clustering
#' @param algorithm The clustering algorithm to be used
#'
#' @return A dataframe with the memberships of the samples found in the input
#' data
#'
#' @export
#'
#' @examples
#' optimalClustering(toy_genes, 4,"spectral")
#' optimalClustering(toy_genes, 2,"kmeans")


optimalClustering <- function(data, clusters, algorithm) {

  print("Running optimal clustering...")

  if (algorithm == "spectral") {

    spectral.kernels <- c("rbfdot", "polydot", "vanilladot", "tanhdot",
                          "laplacedot", "anovadot", "splinedot")

    optimal.stability <- 0
    optimal.memberships <- seq(0,0,length.out=dim(data)[1])

    for (par in spectral.kernels) {

      sc.boot <- clusterboot(data,
                             B = 25,
                             bootmethod = "boot",
                             clustermethod = speccCBI,
                             k = clusters,
                             kernel = par,
                             seed = 28588,
                             showplots = FALSE,
                             count=FALSE)

      if (mean(sc.boot$bootmean) > optimal.stability) {
        optimal.stability <- mean(sc.boot$bootmean)
        optimal.memberships <- sc.boot$partition
        optimal.parameter <- par
      }
    }

  } else if (algorithm == "hierarchical") {

    hierarchical.methods <- c("average", "ward.D", "ward.D2", "single",
                           "complete", "mcquitty", "median", "centroid")

    optimal.stability <- 0
    optimal.memberships <- seq(0,0,length.out=dim(data)[1])

    for (par in hierarchical.methods) {

      sc.boot <- clusterboot(data,
                             B = 25,
                             bootmethod = "boot",
                             clustermethod = hclustCBI,
                             k = clusters,
                             method = par,
                             seed = 28588,
                             showplots = FALSE,
                             count=FALSE)

      if (mean(sc.boot$bootmean) > optimal.stability) {
        optimal.stability <- mean(sc.boot$bootmean)
        optimal.memberships <- sc.boot$partition
        optimal.parameter <- par
      }
    }
  } else {

    kmeans.kernels <- c("Hartigan-Wong", "Lloyd", "Forgy",
                        "MacQueen")

    optimal.stability <- 0
    optimal.memberships <- seq(0,0,length.out=dim(data)[1])

    for (par in kmeans.kernels) {

      sc.boot <- clusterboot(data,
                             B = 25,
                             bootmethod = "boot",
                             clustermethod = kmeansCBI,
                             k = clusters,
                             algorithm = par,
                             seed = 28588,
                             showplots = FALSE,
                             count=FALSE)

      if (mean(sc.boot$bootmean) > optimal.stability) {
        optimal.stability <- mean(sc.boot$bootmean)
        optimal.memberships <- sc.boot$partition
        optimal.parameter <- par
      }
    }
  }

  memberships <- data.frame(id = rownames(data),
                            memberships = optimal.memberships)

  return(list(memberships, optimal.stability, optimal.parameter))
}
